build:
  image: centos:7
  variables:
    OSXCROSS_SDK_VERSION: "10.11"
  script: |
    # Install build dependencies.
    yum -y install epel-release
    yum -y install \
        git \
        make \
        gcc \
        mingw64-gcc \
        mingw32-gcc \
        zip \
        gcc-c++ \
        clang \
        which \
        patch

    export NODE_VERSION=10.15.0
    export GO_VERSION=1.11.4

    (cd /usr/local && curl -L -o - https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz | tar zxf - --strip-components=1)
    (cd /usr/local && curl -L -o - https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz | tar zxf -)

    # Install osxcross.
    export OSXCROSS=${CI_PROJECT_DIR}/osxcross
    if [[ -e "${OSXCROSS}/.cached" ]]; then
        echo "Using cached osxcross."
    else
        git clone https://github.com/tpoechtrager/osxcross.git ${OSXCROSS}
        cd ${OSXCROSS}
        curl -L -o ./tarballs/MacOSX${OSXCROSS_SDK_VERSION}.sdk.tar.xz https://s3.amazonaws.com/andrew-osx-sdks/MacOSX${OSXCROSS_SDK_VERSION}.sdk.tar.xz
        sed -i -e 's|-march=native||g' ./build_clang.sh ./wrapper/build.sh
        printf "\n" | PORTABLE=true ./build.sh
        touch .cached
    fi

    cd ${CI_PROJECT_DIR}
    export GOPATH=/go
    export PATH=${OSXCROSS}/target/bin:$GOPATH/bin:/usr/local/go/bin:$PATH
    make install-deps
    GOOS=linux GOARCH=amd64 make dist
    SKIP_WEBAPP=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 make dist
    #SKIP_WEBAPP=1 CC=i686-w64-mingw32-gcc GOOS=windows GOARCH=386 make dist
    SKIP_WEBAPP=1 CC=o64-clang GOOS=darwin GOARCH=amd64 make dist
    cp dist/*.zip ${CI_PROJECT_DIR}

  cache:
    key: ${OSXCROSS_SDK_VERSION}
    paths:
      - ./osxcross

  artifacts:
    paths:
      - "*.zip"
