image: fedora:29

before_script:
  - yum -y install git make gcc mingw64-gcc mingw32-gcc zip
  - yum -y install go nodejs npm

build:
  script: |
    export GOPATH=/go
    export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
    make install-deps
    GOOS=linux GOARCH=amd64 make dist
    CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 make dist
    CC=i686-w64-mingw32-gcc GOOS=windows GOARCH=386 make dist
    cp dist/*.zip ${CI_PROJECT_DIR}

  artifacts:
    paths:
      - "*.zip"
