build:
  image: centos:7
  before_script:
    - yum -y install epel-release
    - yum -y install git make gcc mingw64-gcc mingw32-gcc zip
    - (cd /usr/local && curl -L -o - https://nodejs.org/dist/v10.14.2/node-v10.14.2-linux-x64.tar.gz | tar zxf - --strip-components=1)
    - (cd /usr/local && curl -L -o - https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz | tar zxf -)
  script: |
    # Install osxcross.
    yum -y install gcc-c++ clang clang++ which patch
    export OSXCROSS_SDK_VERSION=10.11
    cd /opt
    git clone https://github.com/tpoechtrager/osxcross.git
    cd osxcross
    curl -L -o ./tarballs/MacOSX${OSXCROSS_SDK_VERSION}.sdk.tar.xz https://s3.amazonaws.com/andrew-osx-sdks/MacOSX${OSXCROSS_SDK_VERSION}.sdk.tar.xz
    sed -i -e 's|-march=native||g' ./build_clang.sh ./wrapper/build.sh
    printf "\n" | PORTABLE=true ./build.sh

    cd ${CI_PROJECT_DIR}
    export GOPATH=/go
    export PATH=/opt/osxcross/target/bin:$GOPATH/bin:/usr/local/go/bin:$PATH
    make install-deps
    GOOS=linux GOARCH=amd64 make dist
    SKIP_WEBAPP=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 make dist
    SKIP_WEBAPP=1 CC=i686-w64-mingw32-gcc GOOS=windows GOARCH=386 make dist
    SKIP_WEBAPP=1 CC=o64-clang GOOS=darwin GOARCH=amd64 make dist
    cp dist/*.zip ${CI_PROJECT_DIR}

  artifacts:
    paths:
      - "*.zip"
